### ISSUE TITLE
first parameter of .arrayAppend must be a valid path or an empty sting

### ISSUE THREAD

**Issue by ViktorMasnyi** [couchbase/docs-sdk-nodejs#117]
Hi,
seems there is an error in doc - passing false as a first parameter gives "path mismatch" error
https://github.com/couchbase/docs-sdk-nodejs/blob/0fc2edb71cc8974d8b04190a940d6f20f11a3660/modules/howtos/examples/subdoc.js#L112-L116

Server version: 
Enterprise Edition 6.6.0 build 7909
SDK: NodeSDK 3.1.2

**Comment by osfameron** [comment]
Thanks @ViktorMasnyi! I've opened https://issues.couchbase.com/browse/DOC-8975 to track it on our system.
It looks like the correct syntax should be something like `couchbase.MutateInSpec.arrayAppend("", ["elem1", "elem2", "elem3"], { multi: true }),` but I've not tested fully yet.

**Comment by osfameron** [comment]
@ViktorMasnyi thanks again for the report, I've updated the code in https://github.com/couchbase/docs-sdk-nodejs/pull/129
Do let me know if you spot any further issues.
