### ISSUE TITLE
Typo Error in Sub-Document Page

### ISSUE THREAD

**Issue by Dhruv-Aga** [couchbase/docs-sdk-nodejs#78]
I was going through the documentation and try the examples given. I found an error in the Sub-Document Page of Documentation.
The issue was in part:
> var result = await _collecton.LookupIn_('customer123', [
>     couchbase.LookupInSpec.exists('purchases.pending[-1]')
> ]);
> console.log('Path exists? ', result.content[0]);

which should be like below 

> var result = await **collection**.**lookupIn**('customer123', [
>     couchbase.LookupInSpec.exists('purchases.pending[-1]')
> ]);
> console.log('Path exists? ', result.content[0]);

That means:
collecton.LookupIn -> collection.lookupIn

**Comment by RichardSmedley** [comment]
Thanks @Dhruv-Aga - fixed now
